# Generated by Django 5.0.7 on 2024-09-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
