# Generated by Django 5.0.7 on 2024-10-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
