# Generated by Django 5.0.7 on 2024-10-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customerorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
