# Generated by Django 5.0.7 on 2024-11-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_restaurant_menuitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
