# Generated by Django 5.0.7 on 2024-11-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='items', to='customer.category'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='customer.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='customer.restaurant'),
        ),
    ]
