# Generated by Django 5.0.7 on 2024-11-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_customerorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
